spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hibernate_sequence?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: d42377878
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: false
      path: /console
  devtools:
    livereload:
      enabled: true
  thymeleaf:
      cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 850074607366-lnoiha833ukt43deja4vcuacl8malgq2.apps.googleusercontent.com
            client-secret: d3C1le2qA0a8rSYOSywKksm8
          facebook:
            client-id: 1082301592113567
            client-secret: 7005d8be876ee950e000e442650fc81a
custom:
  oauth2:
    kakao:
      client-id: 379ae6393980b6440682f3ea849bce20